export enum Amenity {
    WIFI="Wi-Fi",
    PARKING="Parking",
    POOL="Pool",
    GYM="Gym",
    AIR_CONDITIONING="Air Conditioning",
    BREAKFAST_INCLUDED="Breakfast Included",
    RESTAURANT="Restaurant",
    PET_FRIENDLY="Pet Friendly",
    SPA="Spa",
    TV="TV",
    KITCHENETTE="Kitchenette",
    LAUNDRY="Laundry",
    BALCONY="Balcony",
    BAR="Bar",
    SHUTTLE_SERVICE="Shuttle Service",
    BUSINESS_CENTER="Business Center",
    CONCIERGE="Concierge",
    CHILDREN_PLAY_AREA="Children's Play Area",
    MEETING_ROOMS="Meeting Rooms",
    FITNESS_CLASSES="Fitness Classes"
}